
package com.riege.onerecord.hackathon.ecsd.onerecordCargo;

import java.io.Serializable;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;


/**
 * Superclass: Actors are Persons or entities acting like a single person
 * 
 * This class was generated by OWL2Java 0.22.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Actor)
public class Actor
    extends LogisticsAgent
    implements Serializable
{

    /**
     * Reference to the Organization the Actor is associated with
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_associatedOrganization)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Organization associatedOrganization;

    public void setAssociatedOrganization(Organization associatedOrganization) {
        this.associatedOrganization = associatedOrganization;
    }

    public Organization getAssociatedOrganization() {
        return associatedOrganization;
    }

}
