
package com.riege.onerecord.hackathon.ecsd.onerecordCargo;

import java.io.Serializable;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;


/**
 * Booking object refers to a confirmed booking
 * 
 * This class was generated by OWL2Java 0.22.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Booking)
public class Booking
    extends LogisticsService
    implements Serializable
{

    /**
     * Reference to the BookingOptionRequest the LogisticsObject is detailling
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_forBookingRequest)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected BookingRequest forBookingRequest;
    /**
     * Reference to the Waybill object
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_issuedForWaybill)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Waybill issuedForWaybill;

    public void setForBookingRequest(BookingRequest forBookingRequest) {
        this.forBookingRequest = forBookingRequest;
    }

    public BookingRequest getForBookingRequest() {
        return forBookingRequest;
    }

    public void setIssuedForWaybill(Waybill issuedForWaybill) {
        this.issuedForWaybill = issuedForWaybill;
    }

    public Waybill getIssuedForWaybill() {
        return issuedForWaybill;
    }

}
