
package com.riege.onerecord.hackathon.ecsd.onerecordCargo;

import java.io.Serializable;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;


/**
 * A party, ususally the freight forwarder, creates the BookingRequest in order to inform the Carrier that h wants to confirm a Booking
 * 
 * This class was generated by OWL2Java 0.22.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_BookingRequest)
public class BookingRequest
    extends LogisticsObject
    implements Serializable
{

    /**
     * Reference to the Booking
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_booking)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Booking booking;
    /**
     * Reference to the BookingOptions
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_bookingOption)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected BookingOption bookingOption;

    public void setBooking(Booking booking) {
        this.booking = booking;
    }

    public Booking getBooking() {
        return booking;
    }

    public void setBookingOption(BookingOption bookingOption) {
        this.bookingOption = bookingOption;
    }

    public BookingOption getBookingOption() {
        return bookingOption;
    }

}
