
package com.riege.onerecord.hackathon.ecsd.onerecordCargo;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonProperty;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;


/**
 * Company details
 * 
 * This class was generated by OWL2Java 0.22.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Company)
public class Company
    extends Organization
    implements Serializable
{

    /**
     * Company branches
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_branch)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected CompanyBranch branch;
    /**
     * Name of company or organization
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_companyName)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String companyName;
    /**
     * IATA accredited cargo agent 7 digit number
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_iataCargoAgentCode)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    @JsonProperty("https://onerecord.iata.org:443/ns/cargo#iataCargoAgentCode")
    protected String iataCargoAgentCode;
    /**
     * IATA CASS cargo agent 4 digit branch number / location identifier
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_iataCargoAgentLocationIdentifier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String iataCargoAgentLocationIdentifier;

    public void setBranch(CompanyBranch branch) {
        this.branch = branch;
    }

    public CompanyBranch getBranch() {
        return branch;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setIataCargoAgentCode(String iataCargoAgentCode) {
        this.iataCargoAgentCode = iataCargoAgentCode;
    }

    public String getIataCargoAgentCode() {
        return iataCargoAgentCode;
    }

    public void setIataCargoAgentLocationIdentifier(String iataCargoAgentLocationIdentifier) {
        this.iataCargoAgentLocationIdentifier = iataCargoAgentLocationIdentifier;
    }

    public String getIataCargoAgentLocationIdentifier() {
        return iataCargoAgentLocationIdentifier;
    }

}
