
package com.riege.onerecord.hackathon.ecsd.onerecordCargo;

import java.io.Serializable;
import java.util.Set;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;


/**
 * Action to describe build-up or break-down of LoadingUnits
 * 
 * This class was generated by OWL2Java 0.22.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Composing)
public class Composing
    extends LogisticsAction
    implements Serializable
{

    /**
     * References to the Materials being built-up or broken-down
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_composedMaterials)
    protected Set<LoadingMaterial> composedMaterials;
    /**
     * References to the Pieces being built-up or broken-down
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_composedPieces)
    protected Set<Piece> composedPieces;
    /**
     * Reference to the LoadingUnit being built-up or broken-down
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_loadingUnit)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected LoadingUnit loadingUnit;
    /**
     * Enum stating whether the CompositionAction describes build-up or break-down
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_compositionType)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String compositionType;

    public void setComposedMaterials(Set<LoadingMaterial> composedMaterials) {
        this.composedMaterials = composedMaterials;
    }

    public Set<LoadingMaterial> getComposedMaterials() {
        return composedMaterials;
    }

    public void setComposedPieces(Set<Piece> composedPieces) {
        this.composedPieces = composedPieces;
    }

    public Set<Piece> getComposedPieces() {
        return composedPieces;
    }

    public void setLoadingUnit(LoadingUnit loadingUnit) {
        this.loadingUnit = loadingUnit;
    }

    public LoadingUnit getLoadingUnit() {
        return loadingUnit;
    }

    public void setCompositionType(String compositionType) {
        this.compositionType = compositionType;
    }

    public String getCompositionType() {
        return compositionType;
    }

}
