
package com.riege.onerecord.hackathon.ecsd.onerecordCargo;

import java.io.Serializable;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;


/**
 * Details of the pieces (Live animals) of the permit and specific information such as quantity measured and used to date quota
 * 
 * This class was generated by OWL2Java 0.22.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_EpermitConsignment)
public class EpermitConsignment
    extends LogisticsObject
    implements Serializable
{

    /**
     * Reference to te pieces (Live Animals) of the permit
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_consignmentItems)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected PieceLiveAnimals consignmentItems;
    /**
     * Reference to the Epermit of the consignment
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_epermit)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected LiveAnimalsEpermit epermit;
    /**
     * Quatity measured by the examining authority (box 14)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_examiningQuantity)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value examiningQuantity;
    /**
     * total number of specimens exported in the current calendar year and the current annuela quota for the species concerned (box 11a)
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_usedToDateQuotaQuantity)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#integer", max = 1)
    })
    protected Integer usedToDateQuotaQuantity;

    public void setConsignmentItems(PieceLiveAnimals consignmentItems) {
        this.consignmentItems = consignmentItems;
    }

    public PieceLiveAnimals getConsignmentItems() {
        return consignmentItems;
    }

    public void setEpermit(LiveAnimalsEpermit epermit) {
        this.epermit = epermit;
    }

    public LiveAnimalsEpermit getEpermit() {
        return epermit;
    }

    public void setExaminingQuantity(Value examiningQuantity) {
        this.examiningQuantity = examiningQuantity;
    }

    public Value getExaminingQuantity() {
        return examiningQuantity;
    }

    public void setUsedToDateQuotaQuantity(Integer usedToDateQuotaQuantity) {
        this.usedToDateQuotaQuantity = usedToDateQuotaQuantity;
    }

    public Integer getUsedToDateQuotaQuantity() {
        return usedToDateQuotaQuantity;
    }

}
