
package com.riege.onerecord.hackathon.ecsd.onerecordCargo;

import java.io.Serializable;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;


/**
 * Insurance details
 * 
 * This class was generated by OWL2Java 0.22.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Insurance)
public class Insurance
    extends LogisticsObject
    implements Serializable
{

    /**
     * Party covering the insurance 
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_coveringOrganization)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Organization coveringOrganization;
    /**
     * Insured amount - amount covered by the insurance policy
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_insuredAmount)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value insuredAmount;
    /**
     * Reference to the shipment insured
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_insuredShipment)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Shipment insuredShipment;
    /**
     * When no value is declared for Insurance this field should be completed with the value TRUE otherwise FALSE
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_nvdIndicator)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#boolean", max = 1)
    })
    protected Boolean nvdIndicator;

    public void setCoveringOrganization(Organization coveringOrganization) {
        this.coveringOrganization = coveringOrganization;
    }

    public Organization getCoveringOrganization() {
        return coveringOrganization;
    }

    public void setInsuredAmount(Value insuredAmount) {
        this.insuredAmount = insuredAmount;
    }

    public Value getInsuredAmount() {
        return insuredAmount;
    }

    public void setInsuredShipment(Shipment insuredShipment) {
        this.insuredShipment = insuredShipment;
    }

    public Shipment getInsuredShipment() {
        return insuredShipment;
    }

    public void setNvdIndicator(Boolean nvdIndicator) {
        this.nvdIndicator = nvdIndicator;
    }

    public Boolean getNvdIndicator() {
        return nvdIndicator;
    }

}
