
package com.riege.onerecord.hackathon.ecsd.onerecordCargo;

import java.io.Serializable;
import java.util.Set;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;


/**
 * Common loading unit/container details
 * 
 * This class was generated by OWL2Java 0.22.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_LoadingUnit)
public class LoadingUnit
    extends PhysicalLogisticsObject
    implements Serializable
{

    /**
     * Details of contained (virtual) piece(s)
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_loadedPiecesOnLoadingUnit)
    protected Set<Piece> loadedPiecesOnLoadingUnit;
    /**
     * Tare weight of the empty ULD
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_tareWeight)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value tareWeight;
    /**
     * Remarks or Supplement Information
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_remarks)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String remarks;

    public void setLoadedPiecesOnLoadingUnit(Set<Piece> loadedPiecesOnLoadingUnit) {
        this.loadedPiecesOnLoadingUnit = loadedPiecesOnLoadingUnit;
    }

    public Set<Piece> getLoadedPiecesOnLoadingUnit() {
        return loadedPiecesOnLoadingUnit;
    }

    public void setTareWeight(Value tareWeight) {
        this.tareWeight = tareWeight;
    }

    public Value getTareWeight() {
        return tareWeight;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getRemarks() {
        return remarks;
    }

}
