
package com.riege.onerecord.hackathon.ecsd.onerecordCargo;

import java.io.Serializable;
import java.util.Set;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;


/**
 * Superclass: LogisticsService is a sequence of Activities provided by one Party to another
 * 
 * This class was generated by OWL2Java 0.22.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_LogisticsService)
public class LogisticsService
    extends LogisticsObject
    implements Serializable
{

    /**
     * Information about the Activities that are part of the Service and their sequence
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_activitySequences)
    protected Set<ActivitySequence> activitySequences;
    /**
     * Information about contactDetails
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_contactDetails)
    protected Set<ContactDetail> contactDetails;
    /**
     * References to Actors (Person, NonHumanActor) acting as contacts
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_contactPersons)
    protected Set<Person> contactPersons;

    public void setActivitySequences(Set<ActivitySequence> activitySequences) {
        this.activitySequences = activitySequences;
    }

    public Set<ActivitySequence> getActivitySequences() {
        return activitySequences;
    }

    public void setContactDetails(Set<ContactDetail> contactDetails) {
        this.contactDetails = contactDetails;
    }

    public Set<ContactDetail> getContactDetails() {
        return contactDetails;
    }

    public void setContactPersons(Set<Person> contactPersons) {
        this.contactPersons = contactPersons;
    }

    public Set<Person> getContactPersons() {
        return contactPersons;
    }

}
