
package com.riege.onerecord.hackathon.ecsd.onerecordCargo;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;

import cz.cvut.kbss.jopa.model.annotations.Id;
import cz.cvut.kbss.jopa.model.annotations.OWLAnnotationProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;
import cz.cvut.kbss.jopa.model.annotations.Properties;
import cz.cvut.kbss.jopa.model.annotations.Types;
import cz.cvut.kbss.jopa.vocabulary.RDFS;


/**
 * Logistics Object parent class, containing all common properties for logistics objects.
 * 
 * This class was generated by OWL2Java 0.22.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_LogisticsObject)
public class LogisticsObject
    implements Serializable
{

    @Id(generated = true)
    @JsonProperty("@id")
    protected String id;
    @OWLAnnotationProperty(iri = RDFS.LABEL)
    protected String name;
    @OWLAnnotationProperty(iri = cz.cvut.kbss.jopa.vocabulary.DC.Elements.DESCRIPTION)
    protected String description;
    @Types
    @JsonFormat(with = JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY)
    protected Set<String> types;
    @Properties
    protected Map<String, Set<String>> properties;
    /**
     * References to the CheckActions performed on the object
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_checks)
    protected Set<Check> checks;
    /**
     * Events object
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_events)
    protected Set<LogisticsEvent> events;
    /**
     * References to all associated ExternalReferences
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_externalReferences)
    protected Set<ExternalReference> externalReferences;
    /**
     * Company identifier from the Internet of Logistics of the entity that hosts the object.
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_companyIdentifier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String companyIdentifier;
    /**
     * Indicator whether a logistics object is a skeleton object
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_skeletonIndicator)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#boolean", max = 1)
    })
    protected Boolean skeletonIndicator;

    @JsonProperty("@context")
    protected Object context;

    public Object getContext() {
        return context;
    }

    public void setContext(Object context) {
        this.context = context;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setTypes(Set<String> types) {
        this.types = types;
    }

    public Set<String> getTypes() {
        return types;
    }

    public void setProperties(Map<String, Set<String>> properties) {
        this.properties = properties;
    }

    public Map<String, Set<String>> getProperties() {
        return properties;
    }

    @Override
    public String toString() {
        return ((((("LogisticsObject {"+ name)+"<")+ id)+">")+"}");
    }

    public void setChecks(Set<Check> checks) {
        this.checks = checks;
    }

    public Set<Check> getChecks() {
        return checks;
    }

    public void setEvents(Set<LogisticsEvent> events) {
        this.events = events;
    }

    public Set<LogisticsEvent> getEvents() {
        return events;
    }

    public void setExternalReferences(Set<ExternalReference> externalReferences) {
        this.externalReferences = externalReferences;
    }

    public Set<ExternalReference> getExternalReferences() {
        return externalReferences;
    }

    public void setCompanyIdentifier(String companyIdentifier) {
        this.companyIdentifier = companyIdentifier;
    }

    public String getCompanyIdentifier() {
        return companyIdentifier;
    }

    public void setSkeletonIndicator(Boolean skeletonIndicator) {
        this.skeletonIndicator = skeletonIndicator;
    }

    public Boolean getSkeletonIndicator() {
        return skeletonIndicator;
    }

}
