
package com.riege.onerecord.hackathon.ecsd.onerecordCargo;

import java.io.Serializable;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;


/**
 * Superclass: LogisticsAgents describe acting entities in the logistics supply chain such as persons and organizations
 * 
 * This class was generated by OWL2Java 0.22.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_LogisticsAgent)
public class LogisticsAgent
    extends LogisticsObject
    implements Serializable
{


}
