
package com.riege.onerecord.hackathon.ecsd.onerecordCargo;

import java.io.Serializable;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;


/**
 * Measurements details for Geolocation sensors
 * 
 * This class was generated by OWL2Java 0.22.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_MeasurementsGeoloc)
public class MeasurementsGeoloc
    extends Measurement
    implements Serializable
{


}
