
package com.riege.onerecord.hackathon.ecsd.onerecordCargo;

import java.io.Serializable;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;


/**
 * Measurements details for sensors that are not geolocation sensors
 * 
 * This class was generated by OWL2Java 0.22.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_MeasurementsOther)
public class MeasurementsOther
    extends Measurement
    implements Serializable
{

    /**
     * Value for measurements other than Geolocation, includes value and unit of measure as described in the Interactive Cargo RP
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_otherMeasurement)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = Vocabulary.s_c_Thing, max = 1)
    })
    protected Value otherMeasurement;

    public void setOtherMeasurement(Value otherMeasurement) {
        this.otherMeasurement = otherMeasurement;
    }

    public Value getOtherMeasurement() {
        return otherMeasurement;
    }

}
