
package com.riege.onerecord.hackathon.ecsd.onerecordCargo;

import java.io.Serializable;
import java.util.Set;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;


/**
 * Superclass: PhysicalLogisticObjects represent the digital twin of an object in the logistics suppy chain that physically exist
 * 
 * This class was generated by OWL2Java 0.22.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_PhysicalLogisticsObject)
public class PhysicalLogisticsObject
    extends LogisticsObject
    implements Serializable
{

    /**
     * References to all connected IotDevices
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_attachedIotDevices)
    protected Set<IotDevice> attachedIotDevices;
    /**
     * References to the Actions the object is involved in
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_involvedInActions)
    protected Set<LogisticsAction> involvedInActions;

    public void setAttachedIotDevices(Set<IotDevice> attachedIotDevices) {
        this.attachedIotDevices = attachedIotDevices;
    }

    public Set<IotDevice> getAttachedIotDevices() {
        return attachedIotDevices;
    }

    public void setInvolvedInActions(Set<LogisticsAction> involvedInActions) {
        this.involvedInActions = involvedInActions;
    }

    public Set<LogisticsAction> getInvolvedInActions() {
        return involvedInActions;
    }

}
