
package com.riege.onerecord.hackathon.ecsd.onerecordCargo;

import java.io.Serializable;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;


/**
 * PublicAuthorities are Organizations of the state on public interests, such as customs
 * 
 * This class was generated by OWL2Java 0.22.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_PublicAuthority)
public class PublicAuthority
    extends Organization
    implements Serializable
{


}
