
package com.riege.onerecord.hackathon.ecsd.onerecordCargo;

import java.io.Serializable;
import java.util.Set;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;


/**
 * Sensor measurements details for Geolocation sensors (sensorType = "Geolocation")
 * 
 * This class was generated by OWL2Java 0.22.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_SensorGeoloc)
public class SensorGeoloc
    extends Sensor
    implements Serializable
{

    /**
     * Reference to the measurements recorded by the geolocation sensor
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_measurementsGeoloc)
    protected Set<MeasurementsGeoloc> measurementsGeoloc;

    public void setMeasurementsGeoloc(Set<MeasurementsGeoloc> measurementsGeoloc) {
        this.measurementsGeoloc = measurementsGeoloc;
    }

    public Set<MeasurementsGeoloc> getMeasurementsGeoloc() {
        return measurementsGeoloc;
    }

}
