
package com.riege.onerecord.hackathon.ecsd.onerecordCargo;

import java.io.Serializable;
import java.util.Set;

import cz.cvut.kbss.jopa.model.annotations.OWLClass;
import cz.cvut.kbss.jopa.model.annotations.OWLDataProperty;
import cz.cvut.kbss.jopa.model.annotations.OWLObjectProperty;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraint;
import cz.cvut.kbss.jopa.model.annotations.ParticipationConstraints;


/**
 * Activity to describe storing processes
 * 
 * This class was generated by OWL2Java 0.22.2
 * 
 */
@OWLClass(iri = Vocabulary.s_c_Storage)
public class Storage
    extends LogisticsActivity
    implements Serializable
{

    /**
     * References to all StoringActions performed for the Storing Activity
     * 
     */
    @OWLObjectProperty(iri = Vocabulary.s_p_storingActions)
    protected Set<Storing> storingActions;
    /**
     * Short text holding the process number if necessary
     * 
     */
    @OWLDataProperty(iri = Vocabulary.s_p_storingIdentifier)
    @ParticipationConstraints({
        @ParticipationConstraint(owlObjectIRI = "http://www.w3.org/2001/XMLSchema#string", max = 1)
    })
    protected String storingIdentifier;

    public void setStoringActions(Set<Storing> storingActions) {
        this.storingActions = storingActions;
    }

    public Set<Storing> getStoringActions() {
        return storingActions;
    }

    public void setStoringIdentifier(String storingIdentifier) {
        this.storingIdentifier = storingIdentifier;
    }

    public String getStoringIdentifier() {
        return storingIdentifier;
    }

}
